name: proxydiff-nas-zico
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - scipy=1.12.0
  - scikit-learn=1.5.0
  - pandas=1.5.3
  - pyyaml=6.0.2
  - pillow=10.4.0
  - tqdm=4.67.1
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - thop==0.1.1.post2209072238
